reconfigure optims

diff --git a/.ansible/playbooks/roles/django_manage_content/tasks/main.yml b/.ansible/playbooks/roles/django_manage_content/tasks/main.yml
--- a/.ansible/playbooks/roles/django_manage_content/tasks/main.yml
+++ b/.ansible/playbooks/roles/django_manage_content/tasks/main.yml
@@ -1,11 +1,12 @@
 ---
 - shell: |-
     cd "{{cops_django_vars.provision_dir}}"
-    export NONINTERACTIVE=1
-    .ansible/scripts/call_ansible.sh .ansible/playbooks/db.yml \
-      -e "{only_steps: true,
-           cops_postgresql_s_end_fixperms: true,
-           cops_postgresql_s_managecontent: true}"
+    if ! ( su postgres -c "echo 'SELECT PostGIS_full_version();'|psql -v ON_ERROR_STOP=1  postgis" );then
+      export NONINTERACTIVE=1
+      .ansible/scripts/call_ansible.sh .ansible/playbooks/db.yml \
+        -e "{only_steps: true,
+             cops_postgresql_s_managecontent: true}"
+    fi
   when: "cops_django_vars.docker_has_db"
 - become: true
   become_user: "{{cops_django_vars.user}}"
@@ -13,7 +14,7 @@
 - shell: |-
     cd "{{cops_django_vars.provision_dir}}"
     if ! ( LANG=C LC_ALL=C cops_supervisor.{{cops_django_vars.name}}_ctl status django-{{cops_django_vars.name}} 2>&1 | egrep -iq running; ) ;then
-      cops_supervisor.{{cops_django_vars.name}}_ctl restart django-{{cops_django_vars.name}} restart
+      cops_supervisor.{{cops_django_vars.name}}_ctl restart django-{{cops_django_vars.name}}
       echo schanged >&2
     fi
   register: _cops_django_managecontent_s
